### PR TITLE
Add impact in get history route

### PR DESCRIPTION
**Pull request by kun2985**
# Description

This PR qdd impact in get history route

## Issue (optional)

Issue link: BOT-1340

### CODE REVIEW

**Comment by kun2985** [comment]
jenkins retest this please

**Comment by kun2985** [comment]
jenkins retest this please

**Comment by kun2985** [comment]
jenkins retest this please

**Comment by pthegner** [comment]
You should add a truncate of all history table in the migration (in order to not have disruption without impacts with the history API).

**Pull request merged**
