### PR TITLE
Update requirements.txt for Jinja2

### PR DESCRIPTION
**Pull request by Netmisa**
Screenshot from 2019-04-17 10-53-39

### CODE REVIEW

**Comment by Netmisa** [comment]
Jenkins could you test this please.

**Comment by Netmisa** [comment]
```
[2019-04-17 11:03:13,650] [ERROR] [26314] [            chaos.navitia] call to navitia timeout
[2019-04-17 11:03:13,751] [ERROR] [26314] [            chaos.navitia] call to navitia timeout
[2019-04-17 11:03:13,851] [ERROR] [26314] [            chaos.navitia] call to navitia timeout
```

**Comment by Netmisa** [comment]
Jenkins could you test this please.

**Comment by pthegner** [comment]
retest this please

**Pull request merged**
